server:
  port: 20001
spring:
  application:
    name: rabbit-gateway
  profiles:
    active: local
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
      routes:
        - id: eagle
          uri: lb://eagle
          predicates:
            - Path=/eagle/**
          filters:
            - StripPrefix=1

        - id: rabbit-sso
          uri: lb://rabbit-sso
          predicates:
            - Path=/sso/**
          filters:
            - StripPrefix=1

        - id: rabbit-chaos
          uri: lb://rabbit-chaos
          predicates:
            - Path=/chaos/**
          filters:
            - StripPrefix=1

        - id: rabbit-bmw
          uri: lb://rabbit-bmw
          predicates:
            - Path=/bmw/**
          filters:
            - StripPrefix=1

        - id: rabbit-wl
          uri: lb://rabbit-chaos
          predicates:
            - Path=/wl/**
          filters:
            - StripPrefix=1

        - id: rabbit-docking
          uri: lb://rabbit-chaos
          predicates:
            - Path=/docking/**
          filters:
            - StripPrefix=1

        - id: rabbit-ums
          uri: lb://rabbit-chaos
          predicates:
            - Path=/ums/**
          filters:
            - StripPrefix=1

        - id: rabbit-com
          uri: lb://rabbit-chaos
          predicates:
            - Path=/com/**
          filters:
            - StripPrefix=1

        - id: rabbit-mina
          uri: lb://rabbit-chaos
          predicates:
            - Path=/mina/**
          filters:
            - StripPrefix=1

        - id: rabbit-tpl
          uri: lb://rabbit-tpl
          predicates:
            - Path=/tpl/**
          filters:
            - StripPrefix=1

        - id: rabbit-ws
          uri: lb://rabbit-chaos
          predicates:
            - Path=/ws/**
          filters:
            - StripPrefix=1

        - id: rabbit-rcm
          uri: lb://rabbit-chaos
          predicates:
            - Path=/rcm/**
          filters:
            - StripPrefix=1

      default-filters:
        - name: SwaggerHeaderFilter
        - name: Logger
        - name: SaveSession
      loadbalancer:
        use404: true
  redis:
    database: 0
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-active: 10
  security:
    oauth2:
      hostname: https://sso.hocgin.top
      client:
        registration:
          custom:
            client-id: client_example
            client-secret: hocgin
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
        provider:
          custom:
            user-info-uri: ${spring.security.oauth2.hostname}/oauth/user
            authorization-uri: ${spring.security.oauth2.hostname}/oauth/authorize
            token-uri: ${spring.security.oauth2.hostname}/oauth/token
            user-name-attribute: name
boot:
  sso:
    client:
      authenticated-urls:
        - /login
      ignore-urls: >
        ,/eagle/**
        ,/swagger-resources/configuration/ui
        ,/favicon.ico
        ,/reboot.txt
        ,/robots.txt
        ,/actuator/**
        ,/webjars/**
        ,/ignore
        ,/*/v2/api-docs

        ,/ws/.socket
        ,/ws/ws/info

        ,/com/message/stat
        ,/com/district/tree
        ,/com/project/encoding:*
        ,/com/comment/*/*/_scroll
        ,/com/comment/*/*/_paging
        ,/com/comment/*/*/history/*
        ,/com/comment/*/*/like

        ,/bmw/gateway/result/**

        ,/rcm/doc/*
        ,/rcm/post/*
        ,/rcm/post/_scroll
        ,/rcm/post-category/main
        ,/rcm/post-category/_complete

        ,/chaos/sms-code
        ,/chaos/address4ip
        ,/chaos/logistics-line/_search
        ,/chaos/gumballs/gift
        ,/chaos/wallpaper/**
        ,/chaos/download
        ,/chaos/proxy/*

        ,/wl/logistics-line/_search

        ,/docking/wx/mp/*
        ,/docking/wx/miniapp/*/token2
        ,/docking/wx/miniapp/*/token

        ,/ums/account/*:avatar
        ,/ums/account
        ,/ums/account/me

        ,/mina/game-card/_complete
        ,/mina/game/room/**
        ,/mina/*/game/_paging
        ,/mina/*/game/*
        ,/mina/face/topic
        ,/mina/app-card/_paging
        ,/mina/mobile-wallpaper/_paging
        ,/mina/*/app/_paging
        ,/mina/*/check-message
        ,/mina/*/check-image
        ,/mina/*/mobile-wallpaper/_paging
        ,/mina/*/mobile-wallpaper/random/_paging
        ,/mina/*/mobile-wallpaper/tags/_paging
        ,/mina/youtube/authorize
        ,/mina/youtube/*/callback
        ,/mina/share-content
        ,/mina/recharge/*
        ,/mina/api/recharge/*

        ,/sso/account/login/qrcode
        ,/sso/account/login/token
        ,/sso/account/token/renew
      has-any-role:
        '[/doc.html]':
          - 'ROLE_ADMIN'
          - 'ROLE_API'
  cache:
    names:
      - name: GET_USER_DETAIL
        ttl: 5M
rabbit:
  gateway:
    authorize:
      ignore-urls: ${boot.sso.client.ignore-urls}
