spring:
  security:
    oauth2:
      hostname: http://sso.hocgin.local
  redis:
    host: redis.hocgin.top
    port: 26379
    database: 0
    password: ENC(arDwqcHWrnCjhYGeGX8Pzg==)
boot:
  sso:
    client:
      ignore-urls: >
        /**
