sso:
  oauth:
    clients:
      - client-id: client_example
        client-secret: hocgin
        redirect-uris:
          - https://api.hocgin.top/login/oauth2/code/custom
          - https://sba.hocgin.top/login/oauth2/code/custom
          - https://logistics.hocgin.top/login/oauth2/code/custom
          - https://manage.hocgin.top/login/oauth2/code/custom
