sso:
  oauth:
    clients:
      - client-id: client_example
        client-secret: hocgin
        redirect-uris:
          - https://api-dev.hocgin.top/login/oauth2/code/custom
          - https://sba-dev.hocgin.top/login/oauth2/code/custom
          - https://logistics-dev.hocgin.top/login/oauth2/code/custom
          - https://manage-dev.hocgin.top/login/oauth2/code/custom
