sso:
  oauth:
    clients:
      - client-id: client_example
        client-secret: hocgin
        redirect-uris:
          - https://api.hocgin.top/login/oauth2/code/custom
          - http://api.hocgin.top/login/oauth2/code/custom
          - https://sba.hocgin.top/login/oauth2/code/custom
          - http://sba.hocgin.top/login/oauth2/code/custom
          - https://logistics.hocgin.top/login/oauth2/code/custom
          - http://logistics.hocgin.top/login/oauth2/code/custom
          - https://manage.hocgin.top/login/oauth2/code/custom
          - http://manage.hocgin.top/login/oauth2/code/custom
          - https://bmw.hocgin.top/login/oauth2/code/custom
          - http://bmw.hocgin.top/login/oauth2/code/custom
          - https://arthas.hocgin.top/login/oauth2/code/custom
          - http://arthas.hocgin.top/login/oauth2/code/custom
          - https://vip.hocgin.top/login/oauth2/code/custom
          - http://vip.hocgin.top/login/oauth2/code/custom
spring:
  redis:
    database: 3
