server:
  port: 20000
spring:
  application:
    name: rabbit-sso
  profiles:
    active: local
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 7c8f6909e7226d490bdb
            client-secret: a8d3db4c25c9627e4bc5996f25c45f76a4b2214e
            client-name: Github Login
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
