server:
  port: 20010
spring:
  application:
    name: rabbit-openway
  profiles:
    active: local
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
      routes:
        - id: rabbit-test
          uri: https://www.baidu.com
          predicates:
            - Path=/**
