jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    poolSize: 10
logging:
  level:
    root: WARN
    com.alibaba.nacos: WARN
    com.github.lotus: DEBUG
    in.hocg: DEBUG
  config: classpath:log4j2-boot-local.xml
  file:
    path: /data/logs/app/${spring.application.name:unknown}
    name: ${logging.file.path}/${spring.application.name:unknown}.log
  pattern:
    level: '%5p [%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-Span-Export}]'
spring:
  redis:
    timeout: 10000
    jedis:
      pool:
        max-active: 10
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      validation-query: SELECT 1
      test-while-idle: true
      initial-size: 1
  cloud:
    jmx:
      enabled: true
mybatis-plus:
  mapper-locations: classpath*:/**/xml/*.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
feign:
  hystrix:
    enabled: false
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
  compression:
    request:
      enabled: true
    response:
      enabled: true
boot:
  arthas:
    tunnel-server: wss://arthas.hocgin.top/ws
