apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-chaos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxSurge: 2
#      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: chaos
    spec:
      containers:
        - name: chaos
          image: registry.cn-hongkong.aliyuncs.com/hocgin/chaos:latest
          imagePullPolicy: Always
          args: [ "--spring.profiles.active=${ACTIVE}" ]
          ports:
            - name: web-port
              containerPort: 21000
          envFrom:
            - configMapRef:
                name: cm-service-env
          livenessProbe:
            httpGet:
              path: "/actuator/health"
              port: web-port
            initialDelaySeconds: 100
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 3
            httpGet:
              path: "/actuator/health"
              port: web-port
---
apiVersion: v1
kind: Service
metadata:
  name: sv-chaos
spec:
  type: NodePort
  ports:
    - port: 21000
      targetPort: 21000
      protocol: TCP
  selector:
    app: chaos
