apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-sso-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sso-server
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxSurge: 2
#      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: sso-server
    spec:
      containers:
        - name: sso-server
          image: registry.cn-hongkong.aliyuncs.com/hocgin/sso-server:latest
          imagePullPolicy: Always
          args: [ "--spring.profiles.active=${ACTIVE}" ]
          ports:
            - name: web-port
              containerPort: 20000
          envFrom:
            - configMapRef:
                name: cm-service-env
          livenessProbe:
            httpGet:
              path: "/actuator/health"
              port: web-port
            initialDelaySeconds: 100
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 3
            httpGet:
              path: "/actuator/health"
              port: web-port
---
apiVersion: v1
kind: Service
metadata:
  name: sv-sso-server
spec:
  type: NodePort
  ports:
    - port: 20000
      targetPort: 20000
      protocol: TCP
  selector:
    app: sso-server
