apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: registry.cn-hangzhou.aliyuncs.com/hocgin/gateway
          args: [ "--spring.profiles.active=${ACTIVE}" ]
          ports:
            - containerPort: 20001
          envFrom:
            - configMapRef:
                name: cm-service-env
---
apiVersion: v1
kind: Service
metadata:
  name: sv-gateway
spec:
  type: NodePort
  ports:
    - port: 20001
      targetPort: 20001
      protocol: TCP
  selector:
    app: gateway
