apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-chaos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos
  template:
    metadata:
      labels:
        app: chaos
    spec:
      containers:
        - name: chaos
          image: registry.ap-northeast-1.aliyuncs.com/hocgin/chaos
          imagePullPolicy: Always
          args: [ "--spring.profiles.active=dev" ]
          ports:
            - containerPort: 21000
          envFrom:
            - configMapRef:
                name: cm-service-env
---
apiVersion: v1
kind: Service
metadata:
  name: sv-chaos
spec:
  type: NodePort
  ports:
    - port: 21000
      targetPort: 21000
      protocol: TCP
  selector:
    app: chaos
