apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-openway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: openway
    spec:
      containers:
        - name: openway
          image: registry.cn-hongkong.aliyuncs.com/hocgin/openway:latest
          imagePullPolicy: Always
          args: [ "--spring.profiles.active=${ACTIVE}" ]
          ports:
            - name: web-port
              containerPort: 20010
          envFrom:
            - configMapRef:
                name: cm-service-env
          livenessProbe:
            httpGet:
              path: "/actuator/health"
              port: web-port
            initialDelaySeconds: 100
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sv-openway
spec:
  type: NodePort
  ports:
    - port: 20001
      targetPort: 20001
      protocol: TCP
  selector:
    app: openway
