server:
  port: 20002
spring:
  application:
    name: rabbit-sba
  profiles:
    active: local
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: client_example
            client-secret: hocgin
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
        provider:
          custom:
            user-info-uri: ${boot.web.hostname}/oauth/user
            authorization-uri: ${boot.web.hostname}/oauth/authorize
            token-uri: ${boot.web.hostname}/oauth/token
            user-name-attribute: name

boot:
  sso:
    client:
      ignore-urls:
        - /favicon.ico
        - /actuator/**
  web:
    hostname: https://sso.hocgin.top
