spring:
  datasource:
    url: jdbc:mysql://sv-mysql.basic:3306/db_chaos?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true
  redis:
    database: 3
