logging:
  level:
    root: info

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://39.100.87.79:30962/db_chaos_dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: hocgin
  redis:
    host: 39.100.87.79
    port: 32079
