spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: hocgin
    druid:
      validation-query: SELECT 1
      test-while-idle: true
  redis:
    database: 0
    port: 6379
    timeout: 100
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  server:
    ssl:
      enabled: false
mybatis-plus:
  mapper-locations: classpath*:/**/xml/*.xml

boot:
  oss:
    accessKey: ENC(w1e6RkiL4tuTbasWXZL85UIVvXjfplXuTqV259ztRZ8=)
    secretKey: ENC(lRjG5ydrDnl5oRIGUaQNIdyut+mNoxvkVj2oekmbgN80i93FLfl+cA==)
    space: daigou-test
    domain: http://oss-cn-beijing.aliyuncs.com
    type: AliYun
