spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: hocgin
    druid:
      validation-query: SELECT 1
      test-while-idle: true
  redis:
    database: 0
    port: 6379
    timeout: 1000
mybatis-plus:
  mapper-locations: classpath*:/**/xml/*.xml

boot:
  oss:
    accessKey: ENC(w1e6RkiL4tuTbasWXZL85UIVvXjfplXuTqV259ztRZ8=)
    secretKey: ENC(lRjG5ydrDnl5oRIGUaQNIdyut+mNoxvkVj2oekmbgN80i93FLfl+cA==)
    space: daigou-test
    domain: http://oss-cn-beijing.aliyuncs.com
    type: AliYun
  cache:
    names:
      - name: GUMBALLS_GIFT
        ttl: 1D
      - name: PAGING_WALLPAPER
        ttl: 1D
rabbit:
  wx:
    # https://developers.weixin.qq.com/sandbox
    miniapp:
      configs:
        - appid: wx5b633a935cc7c105
          secret: cc31e7128952ca15f53e9704d87dc43d
    # https://mp.weixin.qq.com/debug/cgi-bin/sandboxinfo?action=showinfo&t=sandbox/index
    mp:
      configs:
        - appid: wx6c554c6d25b19c4a
          secret: ENC(AsBXMuX5bJLMrGbrYFv2h4x6eK+/4HA7q5GtgQG7Y+pAfqP7bFf8JvRSfWHhwF22)
          token: ENC(btL8CAl2j2XmWoBzPm+XcynY2xw6js7P)
