debug: true
logging:
  level:
    root: debug

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://sv-mysql.basic:3306/db_chaos_dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: hocgin
  redis:
    host: sv-redis.basic
    port: 6379
    database: 1
rabbit:
  payment:
    url-prefix: https://api-dev.hocgin.top/pay
