spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: hocgin
    druid:
      validation-query: SELECT 1
      test-while-idle: true
  redis:
    database: 0
    port: 6379
    timeout: 100
mybatis-plus:
  mapper-locations: classpath*:/**/xml/*.xml

boot:
  oss:
    accessKey: ENC(w1e6RkiL4tuTbasWXZL85UIVvXjfplXuTqV259ztRZ8=)
    secretKey: ENC(lRjG5ydrDnl5oRIGUaQNIdyut+mNoxvkVj2oekmbgN80i93FLfl+cA==)
    space: daigou-test
    domain: http://oss-cn-beijing.aliyuncs.com
    type: AliYun

rabbit:
  wx:
    appid: ENC(NkKW1P8WBF4h3NfP860Kj2IOTe5Jo1HEIEUvn/Ktm2A=)
    secret: ENC(AsBXMuX5bJLMrGbrYFv2h4x6eK+/4HA7q5GtgQG7Y+pAfqP7bFf8JvRSfWHhwF22)
    token: ENC(btL8CAl2j2XmWoBzPm+XcynY2xw6js7P)
