server:
  port: 21000
spring:
  application:
    name: rabbit-chaos
  profiles:
    active: local
boot:
  cache:
    names:
      - name: GUMBALLS_GIFT
        ttl: 1D
      - name: PAGING_WALLPAPER
        ttl: 1D
      - name: PAGING_TOPIC_WALLPAPER
        ttl: 1D
      - name: GET_ADDRESS_BY_IP
        ttl: 1H
      # [BMW] 接入应用名称
      - name: GET_ACCESS_MCH_BY_ENCODING
        ttl: 1D
  sentinel:
    flow-rules:
      # 发送短信限流, 24 小时只能发送 5 条
      - resource: GET_SMS_CODE
        grade: 1
        count: 0.01

