spring:
  profiles:
    active: local
  cloud:
    gateway:
      routes:
        - id: payment-chaos
          uri: lb://payment-chaos
          predicates:
            - Path=/chaos/**
          filters:
            - SwaggerHeaderFilter
            - Logger
            - StripPrefix=1
        - id: payment-tpl
          uri: lb://payment-tpl
          predicates:
            - Path=/tpl/**
          filters:
            - SwaggerHeaderFilter
            - Logger
            - StripPrefix=1
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: REQUEST_TIMEOUT, BAD_GATEWAY
            methods: GET, DELETE, PUT
      loadbalancer:
        use404: true
  security:
    oauth2:
      shostname: http://sso.hocgin.top
      client:
        registration:
          custom:
            client-id: client_example
            client-secret: hocgin
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
        provider:
          custom:
            user-info-uri: ${spring.security.oauth2.shostname}/oauth/user
            authorization-uri: ${spring.security.oauth2.shostname}/oauth/authorize
            token-uri: ${spring.security.oauth2.shostname}/oauth/token
            user-name-attribute: name
debug: true
boot:
  sso:
    client:
      ignore-urls:
        - /swagger-resources/configuration/ui
        - /favicon.ico
        - /webjars/**
        - /*/v2/api-docs
        - /ignore
