server:
  port: 20001
  servlet:
    session:
      cookie:
        name: UISESSION
spring:
  profiles:
    active: local
  cloud:
    gateway:
      routes:
        - id: payment-tpl
          uri: lb://payment-tpl
          predicates:
            - Path=/tpl/**
          filters:
            - SwaggerHeaderFilter
            - Logger
            - StripPrefix=1
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: REQUEST_TIMEOUT, BAD_GATEWAY
            methods: GET, DELETE, PUT
      loadbalancer:
        use404: true
  security:
    oauth2:
      shostname: http://sso.hocgin.local:20000
      chostname: http://example.hocgin.local:20001
      client:
        registration:
          custom-client:
            client-id: client_example
            client-secret: hocgin
            provider: custom-provider
            redirect-uri: ${spring.security.oauth2.chostname}/login/oauth2/code/
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          custom-provider:
            user-info-uri: ${spring.security.oauth2.shostname}/user/me
            authorization-uri: ${spring.security.oauth2.shostname}/oauth/authorize
            token-uri: ${spring.security.oauth2.shostname}/oauth/token
            user-name-attribute: name
debug: true
